CREATE TABLE categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name TEXT UNIQUE NOT NULL
);

INSERT INTO categories (category_name) VALUES 
  ('T-Shirts'),
  ('Sweaters'),
  ('Shirts'),
  ('Jeans');