CREATE TABLE listings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  listing_title TEXT NOT NULL,
  listing_gender TEXT CHECK (listing_gender IN ('men', 'women', 'unisex')) NOT NULL,
  listing_category TEXT NOT NULL,
  listing_description TEXT NOT NULL,
  listing_image TEXT NOT NULL,
  listing_slug TEXT NOT NULL,
  listing_uid TEXT NOT NULL,
  listing_price NUMERIC(7, 2) NOT NULL,
  listing_created TIMESTAMP NOT NULL DEFAULT NOW(),
  listing_sold BOOLEAN NOT NULL DEFAULT FALSE,
  listing_user INTEGER NOT NULL REFERENCES users(id)
);