CREATE TABLE orders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_total NUMERIC(7, 2) NOT NULL,
  order_items JSON[] NOT NULL,
  order_shipping_address JSON NOT NULL,
  order_created TIMESTAMP NOT NULL DEFAULT NOW(),
  order_status TEXT NOT NULL DEFAULT 'Pending Shipment',
  order_uid TEXT NOT NULL,
  order_stripe TEXT NOT NULL,
  order_buyer INTEGER NOT NULL REFERENCES users(id),
  order_seller INTEGER NOT NULL REFERENCES users(id)
);