CREATE TABLE purchases (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  purchases_total NUMERIC(7, 2) NOT NULL,
  purchases_items JSON NOT NULL,
  purchases_shipping_address JSON NOT NULL,
  purchases_created TIMESTAMP NOT NULL DEFAULT NOW(),
  purchases_uid TEXT NOT NULL,
  purchases_stripe TEXT NOT NULL,
  purchases_buyer INTEGER NOT NULL REFERENCES users(id)
);